
# taking maven builder to build the package
steps: 
- name: 'maven'
  entrypoint: 'mvn'
  args: ['package', '-DskipTests']
# building a image 
# docker build -t image:tag .
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/devops-mastering/dockerrepo/petclinic:v1', '.']

# docker push image:tag
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/devops-mastering/dockerrepo/petclinic:v1']
