node('docker'){

   stage('Clone petclinicRepository') {
        checkout([$class: 'GitSCM',
            branches: [[name: '*/jenkins-prep']],
            userRemoteConfigs: [[
                url: 'https://github.com/devopsmaster0350/spring-petclinic.git'
            ]]
        ])
   }

   stage('build'){
     sh '''
        mvn clean package 
       '''
   }  
   stage('Archive') {
        archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
    }
   stage('Test Results') {
    junit 'target/surefire-reports/*.xml'
   }

}
